# -*- coding: utf-8 -*-
"""Project 3 - Pandas Project Job Listing_28012026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyTF5nwn99m8ivCVxmKw9LKoirotoZha
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/indeed-job-listings-information.csv')
df.head()

df.shape #(rows, column)

df.info()

# remove duplicates
df = df.drop_duplicates()

df.isnull().sum() # shows no missing data

"""Top Hiring Company"""

df['company_name'].value_counts().head()

"""Most Popular Job Title"""

df['job_title'].value_counts().head()

"""Most Popular Location"""

df['location'].value_counts().head()

"""Salary Analysis"""

import re #re = regular expression, to extract and clean text
def extract_salary(s):
    number = re.findall(r'\d+', str(s))
    if len(number)>=2:
      return(int(number[0]) + int(number[1]))/2
    return None
df['avf_salary'] = df['salary_formatted'].apply(extract_salary)

df[['salary_formatted','avf_salary']].head()

"""Highest Paying Job Title"""

df.groupby('job_title')['avf_salary'].mean().sort_values(ascending=False).head(10)

"""Job Description Text Analysis"""

from collections import Counter
text = ' '.join(df['description_text'].dropna().str.lower())
words = re.findall(r'\b[a-z]{3,}\b', text)

Counter(words).most_common(20)

"""Skill Frequency"""

skills = ['python', 'sql', 'excel', 'power bi', 'machine learning', 'data analysis']
for skill in skills:
  print(skill, text.count(skill))

df['description_text']

"""Data Visualization"""

import matplotlib.pyplot as plt
df['job_title'].value_counts().head(10).plot(kind = 'bar',figsize=(10,5))
plt.title('Top 10 Job Titles')
plt.xticks(rotation=45, ha='right')
plt.show()