# -*- coding: utf-8 -*-
"""Project 1 - Certificate Generator_30102025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-Y2MYyLQnhGtYk1DMfAttwG2muNDdds
"""

!pip install reportlab

import pandas as pd
import numpy as np

from reportlab.lib.pagesizes import landscape,A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

import pandas as pd
import numpy as np
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/dataset.xlsx")
df

# data cleaning
ave = df['Date'].mean()
df['Date'] = df['Date'].fillna(ave)
df
# words formatting
# date format
# missing data

df = df.dropna()
df

# date change format
# create new column with date formatted
df['FormattedDate'] = df['Date'].dt.strftime('%d/%m/%Y')
# dt mean date time
#strftime converts date into string format
# y > 25
# Y >2025

df

# remove old date
df = df.drop('Date', axis =1)
df

# word formatting
df['Course'] = df['Course'].str.capitalize()
df['CourseLevel'] = df['CourseLevel'].str.capitalize()
df

#register the font
font_path = '/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/fonts'

pdfmetrics.registerFont(TTFont('Lora-Bold', font_path + '/Lora-Bold.ttf'))
pdfmetrics.registerFont(TTFont('Lora-Regular', font_path + '/Lora-Regular.ttf'))

# creating the function for the certificate
from re import template
def certificate_generator(name,courseName,CourseLevel,date):
  pdf_file_name = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificates" + name + "-" + courseName + "-" + CourseLevel + ".pdf"
  c = canvas.Canvas(pdf_file_name, pagesize = landscape(A4))
  template = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificate_template.jpg"
  c.drawImage(template,0,0,A4[1], A4[0])
  c.save()

certificate_generator('Dell','Java','advance','20/06/2025')

# Version 2

def certificate_generator(name,courseName,CourseLevel,date):
  pdf_file_name = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificates" + name + "-" + courseName + "-" + CourseLevel + ".pdf"
  c = canvas.Canvas(pdf_file_name, pagesize = landscape(A4))
  template = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificate_template.jpg"
  c.drawImage(template,0,0,A4[1], A4[0])
  print('-------------------')

  # find middle of page (width)
  center_x = c._pagesize[0]/2
  print('Full width of the A4: ', c._pagesize[0])
  print('Center of the A4 (x-axis):', center_x)
  print('-------------------')

  # find middle of page (height)
  center_y = c._pagesize[1]/2
  print('Full height of the A4: ', c._pagesize[1])
  print('Center of the A4 (y-axis):', center_y)
  print('-------------------')
  c.save()

certificate_generator('Dell','Java','advance','20/06/2025')

# Version 3

def certificate_generator(name,courseName,CourseLevel,date):
  pdf_file_name = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificates/" + name + "-" + courseName + "-" + CourseLevel + ".pdf"
  c = canvas.Canvas(pdf_file_name, pagesize = landscape(A4))
  c.drawImage("/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificate_template.jpg",0,0,width = A4[1], height = A4[0])
  center_x = c._pagesize[0]/2
  center_y = c._pagesize[1]/2
  # font for name
  c.setFont('Lora-Bold',30)
  c.drawCentredString(center_x,center_y - 46,name)
  # coursename & courselevel
  c.setFont('Lora-Bold',28)
  c.drawCentredString(center_x,center_y - 105,courseName + '-' +  CourseLevel)
  # date
  c.setFont('Lora-Bold',17)
  c.drawCentredString(center_x + 190,center_y - 160, date)
  # cert ID
  cert_id = 'Cert ID:' + str(pd.Timestamp.now().timestamp()).replace('.','')
  c.setFont('Lora-Regular',12)
  c.drawCentredString(center_x + 266, center_y - 230, cert_id.upper())
  c.save()

# generate unique id based on time
print(pd.Timestamp.now())
print(pd.Timestamp.now().timestamp())
print(str(pd.Timestamp.now().timestamp()).replace('.',""))

for x in range(10):
  print(pd.Timestamp.now())

certificate_generator('Dell','C++','Advance','20/06/2025')

# Version 4

def certificate_generator(name,courseName,CourseLevel,date):
  pdf_file_name = "/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificates/" + name + "-" + courseName + "-" + CourseLevel + ".pdf"
  c = canvas.Canvas(pdf_file_name, pagesize = landscape(A4))
  c.drawImage("/content/drive/MyDrive/Colab Notebooks/1.2 Python Certificate Generator Project (STARTING TEMPLATE)-20251027T123828Z-1-001 /1.2 Python Certificate Generator Project (STARTING TEMPLATE)/certificate_template.jpg",0,0,width = A4[1], height = A4[0])
  center_x = c._pagesize[0]/2
  center_y = c._pagesize[1]/2
  # font for name
  c.setFont('Lora-Bold',30)
  c.drawCentredString(center_x,center_y - 46,name)
  # coursename & courselevel
  c.setFont('Lora-Bold',28)
  c.drawCentredString(center_x,center_y - 105,courseName + '-' +  CourseLevel)
  # date
  c.setFont('Lora-Bold',17)
  c.drawCentredString(center_x + 190,center_y - 160, date)
  # cert ID
  cert_id = 'Cert ID:' + str(int(pd.Timestamp.now().timestamp()))
  c.setFont('Lora-Regular',12)
  c.drawCentredString(center_x + 266, center_y - 230, cert_id.upper())
  c.save()

df

# df.iterrows > gives a loopable array

for index, x in df.iterrows():
  print(x)
  print('----------------------------')

for index, x in df.iterrows():
  certificate_generator(x['Name'],x['Course'],x['CourseLevel'],x['FormattedDate'])
print(str(len(df)) + ' certificate generated succesfully')